### ISSUE TITLE
question about post-processing 

### ISSUE THREAD

**Issue by ohmydroid** [LilianHollard/LeYOLO#13]
Does Le-YOLO share the same post-processing as YOLOV8? or can I view Le-YOLO as a compact version of YOLOV8 by introducing  efficient operator and architecture?

**Comment by LilianHollard** [comment]
Hi! Thank you for your question.
Yes, the post-processing is indeed the same as in YOLOv8.
LeYOLO is a miniature version of YOLO in general. We are also similar to EfficientDet as a low-cost version of object detectors.
