### ISSUE TITLE
无法复现相应的精度

### ISSUE THREAD

**Issue by chenzx2** [LilianHollard/LeYOLO#5]
实测对比发现，精度不是很高，是不是训练的时候有什么需要注意的事项

**Comment by chenzx2** [comment]
LeYolos mAp50: 53%
yolov8n mAp50: 59%

**Comment by LilianHollard** [comment]
Hello,
It depends on your comparison. You are comparing yolov8n with LeYOLOs, whereas yolov8n uses more flop and parameter.

A comparable model would be LeYOLO Large.

**Comment by chenzx2** [comment]
> Hello, It depends on your comparison. You are comparing yolov8n with LeYOLOs, whereas yolov8n uses more flop and parameter.
> 
> A comparable model would be LeYOLO Large.

I change the model of yolov8n, it is same flop and parameter

**Comment by LilianHollard** [comment]
Ok, which dataset are you using ?

**Comment by chenzx2** [comment]
> Ok, which dataset are you using ?

visdrone, my val dataset is smaller than visdrone val dataset

**Comment by LilianHollard** [comment]
Oh, okay, that explains why... I thought it was an issue with MSCOCO.
Well, thank you for the feedback. I will work on other datasets soon, but I will focus on MSCOCO for now.
Therefore, some components in LeYOLO architecture are not optimized for specific object sizes, which might be the case in Visdrone.

**Comment by chenzx2** [comment]
Detect's cv2 and cv3 can indeed reduce a lot of parameter count, and it may be even better to add washerstein-loss. You can also try replacing the backbone with yolov10
